sudo: false
language: python
python:
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - pip install codecov
after_success:
  - codecov

install:
    - pip install tox

script:
    - tox

notifications:
  email: false
  irc:
    channels:
      - "irc.speedrunslive.com#race-tracker"
    on_success: change
    on_failure: always
    use_notice: true
